### ISSUE TITLE
Relative file path

### ISSUE THREAD

**Issue by jim-rosales** [bishthetiger/prj-rev-bwfs-dasmoto#3]
You were close in getting the relative path to work.

The correct path is the following:
```HTML
background-image: url("../images/pattern.jpeg");
```

The reason is because your stylesheet is in a different folder than the target jpeg.
In order to access it, you need to go up a level by using
`../` after that you'll be inside the Resouce directory which contains both the CSS and images folder. After that, all you need to do is select the images folder and the correct file.

```
         Resources
         /       \
       CSS          images
     /                \
 stylesheet       pattern.jpeg
```
Hopefully that makes sense

https://github.com/bishthetiger/prj-rev-bwfs-dasmoto/blob/76f664d5be4baab1381728adbb6f9197bb0b14a3/Dasmoto/resources/css/style.css#L9

**Comment by bishthetiger** [comment]
Yes, corrected and now working... thank you.
